---
title: "R Workshop"
author: "North Park University"
date: "July 16-18, 2019"
output: 
  html_document: 
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: true
      smooth_scroll: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
h3 {
  font-size: 110%;
  color: #993333;
}

h4 {
  font-size: 105%;
}
</style>



## Welcome

* [Workshop Participants](https://docs.google.com/document/d/1pi88Tqayp1A4B8ZEyA-0d6omuUrFsUy7q_DKAoGO-ss/edit?usp=sharing)

    Participants, please add an entry for yourself.

* [**Questions/Comments/Answers/Responses**](https://docs.google.com/document/d/1PKc8DBh3oIxGid43CvhFO0vCqaS9fEep_prD7HxXN9Y/edit?usp=sharing)

    Use this google doc to comment or ask questions.  Feel free to respond to other people's questions.
    
## RStudio set-up

To take full advantage of the workshop, you will want to have
working, up-to-date versions of [R](https://www.r-project.org/) and
[RStudio](https://www.rstudio.com/). There are at least three
options for achieving this:
    
* **Install them locally on your laptop.** Installation is
straightforward. Follow the links above to find download 
and installation instructions for your platform.
   
* **Use an RStudio server account** and work in a browser. If you don't
already have a server account, I can provide one during the workshop, or you
can use the third option.
    
* **Use [rstudio.cloud](https://rstudio.cloud).** You can set
up a free account.
    
If your R set-up is rather old, I recommend updating R, RStudio, and your 
R packages.

## Resources

* [Isolated Statisticians](https://ww2.amstat.org/committees/isostat/isostat.html) -- Join the email list

## Less Volume, More Creativity

### A guiding principle

* [Slides](less-volume/less-volume-slides.html)

### Example: An introduction to R/RStudio/ggformula

* [Tutorial](http://rsconnect.calvin.edu:3939/less-volume-np2019/)
* [Graphics Gallery](https://docs.google.com/presentation/d/1nl3XHQGbYPeG_mf4aBBGaEFDKGerABc3AvuZNA7PsnM/edit?usp=sharing)
* [gggformula website](https://projectmosaic.github.io/ggformula/)
* [mosaic website](https://projectmosaic.github.io/ggformula/)

### More R Examples

* [Examples and Tutorials @ Calvin](http://rsconnect.calvin.edu:3939/connect/#/apps/94/access) [Mostly assembled by Stacy DeRuiter for Intro Biostats]
* [mosaic package website](https://projectmosaic.github.io/mosaic/) -- be sure to look in "Articles"
* [ggformala package website](https://projectmosaic.github.io/ggformula/) 


## R Markdown -- Creating documents in RStudio

### Getting Started with R Markdown 

* [Slides](rmarkdown/rmarkdown-slides.html)
* [Rmd](rmarkdown/rmarkdown-slides.Rmd)
* [R Markdown website](https://rmarkdown.rstudio.com/lesson-1.html)
* [R Markdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)

### Variations on the theme

* [R Markdown format options](https://rmarkdown.rstudio.com/formats.html)
* [learnr tutorials](https://rstudio.github.io/learnr/) -- for interactive documents with live R code blocks 
* [presentations](https://rmarkdown.rstudio.com/lesson-11.html) -- HTML, PDF, or even PowerPoint slides
* [bookdown](https://bookdown.org/) for "books" (great for class notes)
* [blogdown](https://bookdown.org/yihui/blogdown/) for websites

## Data

### Tidy data

* [Tidy Data Slides](tidy-data/tidy-data-slides.html)

### Getting data into R

R and various packages provide tools for importing data from many different
types of file (csv, Excel, SPSS, SAS, google spreadsheets, etc.)

## Data Wrangling with the tidyverse

### 5&frac12; data verbs to get you started

* Data Wrangling in the Tidyverse (Tutorial)
    * <http://rsconnect.calvin.edu/wrangling-np2019/>
    * <http://rpruim.shinyapps.io/wrangling-intro/>

### Beyond the basics: TB Case Study

* Tutorial available at
    * <http://rstudio.calvin.edu:3939/wrangling-TB/>
    * <https://rpruim.shinyapps.io/tidydata-TB-tutorial/>

* Wrangling demonstrated
    * Reshaping: long vs. wide
    * Combining data from multiple sources -- joins
    * Dealing with "data in variables" -- pivoting +  `tidyr::separate()` 
    * Cleaning up other messes 

* Other useful things
    * dates -- [lubridate](https://lubridate.tidyverse.org/) to the rescue
    * extracting numbers -- `readr::parse_number()` and friends to the rescue
    
* Guns Example
    * [Guns example](Guns.html)
    * data [here](data/Guns.Rds)

## Writing functions in R

* [Slides](writing-functions/tom-dick-harry-slides.html)
* [Tutorial](http://rsconnect.calvin.edu:3939/writing-functions-2019/)

## Shiny Apps

* [Confidence Interval](http://shiny.calvin.edu/rpruim/CIs/)

## Using Github with RStudio

## Creating an R package

* [Making an R package with RStudio and GitHub](http://rpruim.github.io/talks/R-Packages/R-packages-slides.html)

## Maps

* easy maps with leaflet 

## Modeling

* lm(), glm(), lmer(), etc.
* machine learning in R 
* Bayesian inference in R 
* ???

